#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <actiontest_icons.h>

int32_t actiontest_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm actiontest!");

    return 0;
}
