#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <bad_lint_icons.h>

int32_t bad_lint_app(void* p) {
    FURI_LOG_I("TEST", "Hello world");


    FURI_LOG_I("TEST", "I'm bad_lint!");

    return 0; }
